# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual

addons:
  apt:
    packages:
      - libnetcdf-dev
